// <auto-generated />
using System;
using ApiCRUDWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCRUDWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240616041157_ConectToPostgreSQL")]
    partial class ConectToPostgreSQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiCRUDWeb.Models.Pet", b =>
                {
                    b.Property<Guid?>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("ApiCRUDWeb.Models.PetDetails", b =>
                {
                    b.Property<Guid>("PetDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EyesColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Heigth")
                        .HasColumnType("float");

                    b.Property<string>("NonPredominantColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pelage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PredominantColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TongueColor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PetDetailsId");

                    b.HasIndex("PetId")
                        .IsUnique()
                        .HasFilter("[PetId] IS NOT NULL");

                    b.ToTable("PetsDetails");
                });

            modelBuilder.Entity("ApiCRUDWeb.Models.User", b =>
                {
                    b.Property<Guid?>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("EmailAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ApiCRUDWeb.Models.Institution", b =>
                {
                    b.HasBaseType("ApiCRUDWeb.Models.User");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Institution");
                });

            modelBuilder.Entity("ApiCRUDWeb.Models.Owner", b =>
                {
                    b.HasBaseType("ApiCRUDWeb.Models.User");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Owner");
                });

            modelBuilder.Entity("ApiCRUDWeb.Models.Pet", b =>
                {
                    b.HasOne("ApiCRUDWeb.Models.User", "Tutor")
                        .WithMany("Pets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("ApiCRUDWeb.Models.PetDetails", b =>
                {
                    b.HasOne("ApiCRUDWeb.Models.Pet", "Pet")
                        .WithOne("Details")
                        .HasForeignKey("ApiCRUDWeb.Models.PetDetails", "PetId");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("ApiCRUDWeb.Models.Pet", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("ApiCRUDWeb.Models.User", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
