services:
  api:
    container_name: web-api
    build:
        dockerfile: Dockerfile
        context: .
    ports:
       - 5000:8080
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    depends_on: ["web-api-sql"]
    networks:
        redes-api:
    
  web-api-sql:
    image: mcr.microsoft.com/mssql/server
    environment: 
     - "ACCEPT_EULA=Y"
     - "MSSQL_SA_PASSWORD=@Evsgdrb2020"
    volumes:
     - web-api-sql-vol:/var/opt/mssql
    networks:
        redes-api:
            aliases:
                - "sql"    

volumes:
  web-api-sql-vol:
    
networks:
    redes-api:
        driver: bridge
